routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth/login');
})->name('login');

/*Route::get('/hola/{nombre}',function ($nombre){

	echo "hola, esto es una prueba ".$nombre;
});

Route::get('/prueba/{nombre?}',function ($nombre="no hay nombre"){

	echo "hola esto es una prueba ".$nombre;
});

Route::group(['prefix' => 'article'],function(){

	Route::get('/view/{id}',[

		'uses' => 'TestController@view',#nombrecontrolador@metodo
		'as'   => 'articleView'
		]);


});*/

Route::group(['prefix' => 'admin','middleware'=>'auth'],function(){

	Route::resource('users','UsersController');
	Route::get('users/{id}/destroy', 'UsersController@destroy')->name('users.destroy');
	#forma de hacer el as => nombre en laravel 5.4

	Route::resource('categories','CategoriesController');
	Route::get('categories/{id}/destroy', 'CategoriesController@destroy')->name('categories.destroy'); #es para crear una ruta de de tipo DELETE para poder eliminar un registro de la base de datos

	Route::resource('tags','TagsController');
	Route::get('tags/{id}/destroy', 'tagsController@destroy')->name('tags.destroy');

	Route::resource('articles','ArticlesController');
	Route::get('articles/{id}/destroy', 'ArticlesController@destroy')->name('articles.destroy');

	Route::get('images','ImagesController@index')->name('images.index');


});


Auth::routes();



Route::get('/home', 'HomeController@index')->name('home');

#rutas del front
#funcion raiz del proyecto nombre/public/

Route::get('/','FrontController@index')->name('front.index');

Route::get('categories/{name}','FrontController@searchCategory')->name('search.category');

Route::get('tags/{name}','FrontController@searchTag')->name('search.tag');

Route::get('articles/{slug}','FrontController@viewArticle')->name('view.article');

resources/views/admin/errors.blade.php
	@if(count($errors) > 0)

		<div class="alert alert-danger" role="alert">
			<p>¡Error!</p>
			<ul>
				@foreach($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>

		</div>
	@endif

resources/views/admin/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>hola</title>
    <link rel="stylesheet" type="text/css" href="{{asset('bootstrap/plugins/css/bootstrap.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('chosen/chosen.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('trumbowyg/dist/ui/trumbowyg.min.css')}}">

    <script type="text/javascript" src="{{ asset('jquery/jquery-3.2.1.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bootstrap/plugins/js/bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('chosen/chosen.jquery.js') }}"></script>
    <script type="text/javascript" src="{{ asset('trumbowyg/dist/trumbowyg.js') }}"></script>
    <script type="text/javascript" src="{{ asset('trumbowyg/dist/langs/es.min.js') }}"></script>
    
</head>
<body>


	<nav>
		<div class="container">
		@include('admin.nav')<!--estoy incluyendo un nav bar de otra vista llamada nav.blade.php  
							que se encuentra en la carpeta admin,esto se llaman parciales-->
		</div>
	</nav>
	<section>
		<div class="container">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 align="center"> @yield('title')</h4>
				</div>
				<div class="panel-body">
						@include('flash::message')
						@include('admin.errors')
	     				@yield('content')
	     		</div>

	     	</div>
	    </div>
	</section>
	

	<footer >
			<div class="container">
		    	<nav class="navbar navbar-default navbar">
  		    		<div class="container">
  		    			<div class="collapse navbar-collapse">
  		    				<p class="navbar-text">Utilización de laravel 5.4 {{ date('Y') }}
  		    				</p>
  		    				<p class="navbar-text navbar-right">Juan Espinosa</p>
  		    						
  		    			</div>
  		    		</div>
		    	</nav>
		    </div>
		
	</footer>
	@yield('js')
 </body>
</html>

resources/views/admin/nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ route('home') }}">Administración</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{ route('home') }}">Inicio <span class="sr-only">(current)</span></a></li>
        <li><a href="{{ route('users.index')}}">Usuario <span class="sr-only">(current)</span></a></li>
        <li><a href="{{ route('categories.index')}}">Categorías</a></li>
        <li><a href="{{ route('articles.index')}}">Artículos</a></li>
         <li><a href="{{ route('images.index') }}">Imágenes</a></li>
          <li><a href="{{ route('tags.index')}}">Tags</a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          {{ Auth::user()->name }}<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                    <a href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                  document.getElementById('logout-form').submit();">
                                    Cerrar Sesión 
                    </a>

                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                </form>
              </li>
           </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>